### ISSUE TITLE
pip3 install/upgrade does not fetch latest versions

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/GrimoireELK#81] opened 2017-04-15 13:52 UTC
I installed the grimoire-elk and grimoire-kidash python packages earlier (through pip package manager). This also pulled in the perceval package.

At that time I was on versions: grimoire-elk 0.22.1, grimoire-kidash 0.22.1, and perceval 0.5.0.

I wanted to update the packages so I could use the Slack backend which is now available in perceval 0.7.0. So I ran the following commands:

pip3 install grimoire-elk --upgrade
pip3 install grimoire-kidash --upgrade

The first command showed me some upgrade messages in the terminal, no warning/errors. The second command resulted in 'already up to date' messages in the terminal.

After, I am on versions; grimoire-elk 0.22.1, grimoire-kidash 0.22.1, and perceval 0.6.0.

Looks like grimoire-elk and grimoire-kidash where not updated. I was expecting the latest version/release 0.26 as available on github here.

Perceval did get upgraded to 0.6.0, but not to 0.7.0.

The question is, if this is due to something in pip package configs? Or do I need to upgrade in a different way?

**Comment by robinmuilwijk** [comment] 2017-04-15 13:57
I did a quick look on the pypi site. Looks like grimoire-elk and grimoire-kidash are only available as 0.22.1. See https://pypi.python.org/pypi/grimoire-elk/0.22.1.

This would explain only perceval would be upgraded.

**Comment by jgbarah** [comment] 2017-04-16 18:03
Thx a lot, @robinmuilwijk. Yes, you're right, the problem is that new versions are not in pypi yet. I will try to fix that asap. Thanks a lot for the heads-up.

**Comment by jgbarah** [comment] 2017-04-16 22:52
New packages uploaded to Pypi. Closing this issue. Thanks, @robinmuilwijk

**Closed by jgbarah** 2017-04-16 22:52 UTC

**Comment by robinmuilwijk** [comment] 2017-04-17 04:50
Thanks!

**Comment by robinmuilwijk** [comment] 2017-04-17 06:59
Upgrade went fine, tested my data load scripts and all works.

Only thing I noticed is that grimoire-kidash is still on version 0.22.1.
