### ISSUE TITLE
KeyError: 'updated_on' from ocean/elastic.py

### ISSUE THREAD

**Issue by sanacl** [grimoirelab/GrimoireELK#5] opened 2016-04-07 12:50 UTC
```
2016-04-07 12:47:46,309 Error feeding ocean from git (http://git.eclipse.org/gitroot/gemini.naming/org.eclipse.gemini.naming.git): 'updated_on'
Traceback (most recent call last):
  File "/home/bitergia/GrimoireELK/utils/grimoire/arthur.py", line 75, in feed_backend
    ocean_backend.feed()
  File "/home/bitergia/GrimoireELK/utils/grimoire/ocean/elastic.py", line 125, in feed
    self.add_update_date(item)
  File "/home/bitergia/GrimoireELK/utils/grimoire/ocean/elastic.py", line 89, in add_update_date
    entry_lastUpdated = datetime.fromtimestamp(item['updated_on'])
KeyError: 'updated_on'
```

**Comment by sanacl** [comment] 2016-04-07 12:52
I'm using master

**Comment by acs** [comment] 2016-04-07 13:22
This error is because the data from perceval does not seem to be the last version. Are you using perceval 0.1.0? In this version, item['updated_on'] must be defined.

**Comment by acs** [comment] 2016-04-07 13:30
It is not a bug, just trying to use and old index format with the code (0.1) expecting the new format version. I close this bug.

**Closed by acs** 2016-04-07 13:30 UTC

**Comment by sanacl** [comment] 2016-04-07 14:21
It makes sense, I used an older version to get data, updated after it finished and got this error. Thank you Alvaro! :heart_eyes:
